config/routes.rb
Rails.application.routes.draw do
  get 'charges/create'

  get 'charges/new'

  get 'cart/add_to_cart'

  get 'cart/view_order'

  get 'cart/checkout'

  get 'charges/create'

  get 'charges/new'

  # add the below line:

  resources :charges
    post 'order_complete' => 'cart#order_complete'
  devise_for :users
    post 'add_to_cart' => 'cart#add_to_cart'

    get 'view_order' => 'cart#view_order'

    get 'checkout' => 'cart#checkout'

    root 'storefront#all_items'

    get 'categorical' => 'storefront#items_by_category'

    get 'branding' => 'storefront#items_by_brand'

    get 'storefront/all_items'

    get 'storefront/items_by_category'

    resources :products

    get 'sign_out' => 'users/sign_out'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'storefront#all_items'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  belongs_to :user, optional: true

  serialize :order_items, Hash
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  paginates_per 6

  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  @products = Product.all

  protect_from_forgery with: :exception

  before_action :categories, :brands

  def categories
  	@categories = Category.order(:name)
  end

  def brands
    @brands = Product.pluck(:brand).sort.uniq
  end

  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :authenticate_user!, except: [:add_to_cart, :view_order]

  def add_to_cart
    @order = current_order

    line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])
    @order.save
    session[:order_id] = @order.id

    line_item.update(line_item_total: (line_item.product.price * line_item.quantity))

    redirect_back(fallback_location: root_path)
  end

  def view_order
    @line_items = current_order.line_items
  end

  def checkout
    line_items = current_order.line_items

    if line_items.length != 0
      current_order.update(user_id: current_user.id, subtotal: 0)

      @order = current_order

      line_items.each do |line_item|
        line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
        @order.order_items[line_item.product_id] = line_item.quantity
        @order.subtotal += line_item.line_item_total
      end
    end
    @order.save

    @order.update(sales_tax: (@order.subtotal * 0.08))
    @order.update(grand_total: (@order.sales_tax + @order.subtotal))

    line_items.destroy_all
    session[:order_id] = nil
  end
  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
    :email => current_user.email,
    :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
    :customer => customer.id,
    :amount => @amount,
    :description => 'Rails Stripe customer',
    :currency => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = Product.all.page(params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
    @products = Product.all
    @products = Product.all.page(params[:page])
  end

  def items_by_category
    #to get to this page: catergorical_path(params[:category_id])
    @products = Product.where(category: params[:category_id]).page(params[:page])
    @category = Category.find(params[:category_id])
  end

  def items_by_brand
    @products = Product.where(brand: params[:brand]).page(params[:page])
    @brand = params[:brand]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/checkout.html.erb
<h1>Thanks for Shopping With Us!</h1>
<p>Let's review your order:</p>


<% @order.order_items.each do |key, value| %>
  <ol>
    <li><%= Product.find(key).name %></li>
    <li>Qty: <%= value %></li>
  </ol>
<% end %>

<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.subtotal %>
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %>
</p>

<p>
  <strong>Order Total: </strong><%= number_to_currency @order.grand_total %>
</p>

<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>

    <script src="http://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @order.id %>"
    data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eCommerce</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
</head>

<body>
  <nav id='navbar' class='navbar-collapse collapse'>
    <ul>
      <li><%= link_to 'Make New Product', new_product_path, class: 'btn btn-default' %></li>
      <li><a href="/storefront/all_items">All Products</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% @categories.each do |category| %>
          <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
          <% end %>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% @brands.each do |brand| %>
          <li><%= link_to brand, branding_path(brand: brand) %></li>
          <% end %>
          <li><%= link_to 'All', root_path %></li>
        </ul>
      </li>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="/view_order">View Cart</a></li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.avatar.url, style: 'border-radius: 5px; width: 35px; height: 35px;' if !current_user.avatar.blank? %> Hello, <%= current_user.username %>! <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </ul>
    </nav>
    <% if notice != nil %>
      <p id='notice' class='alert alert-info'><%= notice %></p>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script>
      $(function() {
        $('#resizable').resizable({
          ghost: true
        });
      });
      $(function() {
        $('*').disableSelection();
      });
    </script>
  </body>
  </html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class='form-group'>
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class='form-group'>
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class='form-group'>
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class='form-group'>
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand %>
  </div>

  <div class="form-group">
    <%= form.select :category_id, @categories.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a category" } %>
  </div>

  <div class="form-group">
    <strong>Upload Product Image(Optional):</strong>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table class='table' id='resizable'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Category</th>
      <th colspan="3">Configuration</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class='name'><%= product.name %></td>
        <td class='price'><%= number_to_currency product.price %></td>
        <td class='quantity'><%= product.quantity %></td>
        <td class='description white'><%= product.description %></td>
        <td class='brand white'><%= link_to product.brand, branding_path(brand: product.brand) %></td>
        <td class='category'><%= link_to product.category.name, categorical_path(category_id: product.category.id) %></td>
        <td><%= link_to 'Show', product, class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: "Are you sure?\nThis action cannot be undone." }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @products %>
<br>

<%= link_to 'New Product', new_product_path, class: 'btn btn-default' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_loop.html.erb
<% @products.each do |product| %>
<div class="col-md-4">
  <div class="well center-it">
    <% if !product.image.url.blank? %>
    <p><%= image_tag product.image.url, class: "storefront-pics" %></p>
    <% end %>
    <h3><%= link_to product.name, product %></h3>
    <p><%= number_to_currency product.price %></p>
    <p>
      <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>" class='btn btn-primary'>
        <span class="glyphicon glyphicon-plus"></span> Quick Info
      </a>
    </p>
    <% if product.quantity != 0 %>
    <p>
      <%= product.quantity %> <%= product.name %>s left!<br />
      <% unless product.quantity >= 1000 %>
      <br />
        <%= link_to 'Restock', edit_product_path(product), class: 'restock' %>
      <% else %>
      <% unless product.name.include? 'sh' %>
        <p>No need to restock <%= product.name %>s!</p>
      <% else %>
        <p>No need to restock <%= product.name %>es!</p>
      <% end %>
      <% end %>
    </p>
    <% else %>
    <p>
      No more <%= product.name %>s!
      Restock on <%= product.name %>s <%= link_to 'now.', edit_product_path(product), class: 'restock' %>
    </p>
    <% end %>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel_<%= product.id %>">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
      </div>
      <div class="modal-body">
        <p><%= product.description %></p>
      </div>
      <div class="modal-footer">
        <% if product.quantity > 0 %>
          <p>
            <%= form_tag add_to_cart_path do %>
            <%= hidden_field_tag :product_id, product.id %>
            <%= number_field_tag :quantity, nil, placeholder: "How many?" %>
            <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
            <% end %>
          </p>
        <% else %>
          <p>
            No more <%= product.name %>s!
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
<%= paginate @products %>

app/views/storefront/all_items.html.erb
<h1>Welcome to Dete!!!</h1>

<div class="row">
  <%= render 'loop' %>
</div>

app/views/storefront/items_by_brand.html.erb
<h1>Here are our <%= @brand %> products</h1>
<div class="row">
  <%= render 'loop' %>
</div>

app/views/storefront/items_by_category.html.erb
<h1>All of our <%= @category.name %></h1>

<div class="row">
  <%= render 'loop' %>
</div>